name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./OceanWebSystems.EnumEntity/
    - name: Build
      run: dotnet build --no-restore ./OceanWebSystems.EnumEntity/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./OceanWebSystems.EnumEntity/
    - name: Pack
      run: dotnet pack ./OceanWebSystems.EnumEntity/OceanWebSystems.EnumEntity/OceanWebSystems.EnumEntity.csproj --output nupkgs
